export const strings = {
  en: {
    startButton: 'Start My Journey',
    watchDemo: 'Watch Demo',
    analyze: 'Analyzing your idea...',
    checking: 'Checking market data...',
    preparing: 'Preparing your journey...',
    idea: 'Your Idea',
    context: 'Your Context',
    profile: 'Your Profile',
    language: 'Choose Language',
    next: 'Next',
    back: 'Back',
    complete: 'Complete Setup',
    ideaPlaceholder: 'Describe your social startup idea... Why does India need this? (e.g., A WhatsApp bot helping farmers get organic soil deals in Telangana)',
    namePlaceholder: 'e.g., Rahul',
    cityPlaceholder: 'e.g., Warangal, Nizamabad',
    collegePlaceholder: 'NIT Warangal, JNTU...',
    startSimulation: 'Start Your Simulation',
    tryAgain: 'Try Again',
    tryAnotherModule: 'Try Another Module',
    discussCoach: 'Discuss with AI Coach',
    downloadReport: 'Download Report',
    yourScore: 'Your Score',
    goldenFormula: 'The Golden Formula',
    pitfalls: 'Avoidable Pitfalls',
    analyzing: 'Analyzing your idea...',
  },
  hi: {
    startButton: 'अपनी यात्रा शुरू करें',
    watchDemo: 'डेमो देखें',
    analyze: 'आपके विचार का विश्लेषण हो रहा है...',
    checking: 'बाज़ार डेटा जांचा जा रहा है...',
    preparing: 'आपकी यात्रा तैयार हो रही है...',
    idea: 'आपका विचार',
    context: 'आपका संदर्भ',
    profile: 'आपकी प्रोफ़ाइल',
    language: 'भाषा चुनें',
    next: 'आगे',
    back: 'वापस',
    complete: 'सेटअप पूरा करें',
    ideaPlaceholder: 'अपना सामाजिक स्टार्टअप विचार बताएं...',
    namePlaceholder: 'जैसे, राहुल',
    cityPlaceholder: 'जैसे, लखनऊ, जयपुर',
    collegePlaceholder: 'कॉलेज/संस्था का नाम',
    startSimulation: 'सिमुलेशन शुरू करें',
    tryAgain: 'फिर कोशिश करें',
    tryAnotherModule: 'दूसरा मॉड्यूल आज़माएं',
    discussCoach: 'AI कोच से चर्चा करें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    yourScore: 'आपका स्कोर',
    goldenFormula: 'स्वर्णिम सूत्र',
    pitfalls: 'टालने योग्य गलतियाँ',
    analyzing: 'विश्लेषण हो रहा है...',
  },
  te: {
    startButton: 'నా ప్రయాణం ప్రారంభించు',
    watchDemo: 'డెమో చూడు',
    analyze: 'మీ ఆలోచన విశ్లేషిస్తున్నాం...',
    checking: 'మార్కెట్ డేటా తనిఖీ చేస్తున్నాం...',
    preparing: 'మీ ప్రయాణం సిద్ధం చేస్తున్నాం...',
    idea: 'మీ ఆలోచన',
    context: 'మీ సందర్భం',
    profile: 'మీ ప్రొఫైల్',
    language: 'భాష ఎంచుకోండి',
    next: 'తదుపరి',
    back: 'వెనుకకు',
    complete: 'సెటప్ పూర్తి చేయండి',
    ideaPlaceholder: 'మీ సోషల్ స్టార్టప్ ఆలోచన వివరించండి...',
    namePlaceholder: 'ఉదా., రాహుల్',
    cityPlaceholder: 'ఉదా., వరంగల్, నిజామాబాద్',
    collegePlaceholder: 'కళాశాల/సంస్థ పేరు',
    startSimulation: 'సిమ్యులేషన్ ప్రారంభించండి',
    tryAgain: 'మళ్ళీ ప్రయత్నించండి',
    tryAnotherModule: 'వేరే మాడ్యూల్ ప్రయత్నించండి',
    discussCoach: 'AI కోచ్‌తో చర్చించండి',
    downloadReport: 'నివేదిక డౌన్‌లోడ్ చేయండి',
    yourScore: 'మీ స్కోర్',
    goldenFormula: 'స్వర్ణ సూత్రం',
    pitfalls: 'నివారించగలిగే పొరపాట్లు',
    analyzing: 'విశ్లేషిస్తున్నాం...',
  },
  ta: {
    startButton: 'என் பயணத்தை தொடங்கு',
    watchDemo: 'டெமோ பார்',
    analyze: 'உங்கள் யோசனை பகுப்பாய்வு செய்யப்படுகிறது...',
    checking: 'சந்தை தரவு சரிபார்க்கப்படுகிறது...',
    preparing: 'உங்கள் பயணம் தயாரிக்கப்படுகிறது...',
    idea: 'உங்கள் யோசனை',
    context: 'உங்கள் சூழல்',
    profile: 'உங்கள் சுயவிவரம்',
    language: 'மொழி தேர்வு',
    next: 'அடுத்து',
    back: 'பின்',
    complete: 'அமைப்பை முடிக்கவும்',
    ideaPlaceholder: 'உங்கள் சமூக தொடக்கம் யோசனையை விவரிக்கவும்...',
    namePlaceholder: 'எ.கா., ராகுல்',
    cityPlaceholder: 'எ.கா., கோயம்புத்தூர், மதுரை',
    collegePlaceholder: 'கல்லூரி/நிறுவனம்',
    startSimulation: 'சிமுலேஷன் தொடங்கு',
    tryAgain: 'மீண்டும் முயற்சி',
    tryAnotherModule: 'வேறு தொகுதி',
    discussCoach: 'AI பயிற்சியாளரிடம் பேசுங்கள்',
    downloadReport: 'அறிக்கை பதிவிறக்கம்',
    yourScore: 'உங்கள் மதிப்பெண்',
    goldenFormula: 'தங்க சூத்திரம்',
    pitfalls: 'தவிர்க்கக்கூடிய தவறுகள்',
    analyzing: 'பகுப்பாய்வு செய்கிறோம்...',
  }
};
