import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    tagline: 'Your AI Entrepreneurship Companion',
    heroTitle: '4 Crore Students. Millions of Ideas.',
    heroSubtitle: 'Less than 1% Get Real Guidance.',
    heroDesc: 'UdyamPath is your multilingual AI mentor — validate your idea, simulate your startup journey, and get personalized resources.',
    startJourney: 'Start My Journey',
    watchDemo: 'Watch Demo',
    validateIdea: 'Validate Your Idea',
    playSimulation: 'Play Simulation',
    growthPath: 'Growth Path',
    aiCoach: 'AI Coach',
    ideaPlaceholder: 'Describe your social startup idea... (any language)',
    whatIsYourIdea: 'What is your idea?',
    analyzeIdea: 'Analyze My Idea',
    generating: 'Generating...',
    loading: 'Loading...',
    budget: 'Budget',
    morale: 'Team Morale',
    trust: 'Community Trust',
    impact: 'Social Impact',
    month: 'Month',
    turn: 'Turn',
    yourDecision: 'Your Decision',
    consequence: 'Consequence',
    lesson: 'Real-World Lesson',
    nextTurn: 'Next Turn',
    growthDashboard: 'Growth Dashboard',
    weaknesses: 'Areas to Improve',
    resources: 'Curated Resources',
    actionPlan: 'This Week\'s Action Plan',
    chat: 'Chat with Coach',
    sendMessage: 'Send',
    typingMessage: 'AI Coach is thinking...',
    language: 'Language',
    switchLang: 'Switch Language',
    score: 'Score',
    problem: 'Problem Validity',
    audience: 'Target Audience',
    market: 'Market Size',
    uniqueness: 'Uniqueness',
    emotionalMsg: 'Your idea could impact',
    lakhs: 'lakh people',
    startSimulation: 'Start Simulation',
    viewDashboard: 'View Growth Dashboard',
    chatWithCoach: 'Talk to AI Coach',
    schemes: 'Government Schemes',
    videos: 'Learning Videos',
    impactScore: 'Impact Score',
    sustainability: 'Sustainability',
    teamHealth: 'Team Health',
    communityTrust: 'Community Trust',
    selectLanguage: 'Select Your Language',
    continueBtn: 'Continue',
    yourLocation: 'Your Location',
    yourBudget: 'Starting Budget',
    yourSector: 'Sector',
    yourStage: 'Stage',
    locationOptions: ['Tier-1 City', 'Tier-2 City', 'Tier-3 City / Rural'],
    budgetOptions: ['< ₹10,000', '₹10,000 - ₹50,000', '₹50,000 - ₹2 Lakh', '> ₹2 Lakh'],
    sectorOptions: ['Education', 'Health', 'Agriculture', 'Women Empowerment', 'Environment', 'Skill Development', 'Other'],
    stageOptions: ['Just an idea', 'Validated idea', 'Early prototype', 'Have some users'],
    ideaValidation: 'Idea Validation Report',
    simulationTitle: 'UdyamBoard Simulation',
    dashboardTitle: 'Your Growth Dashboard',
    coachTitle: 'AI Coach',
  },
  hi: {
    tagline: 'आपका AI उद्यमिता साथी',
    heroTitle: '4 करोड़ छात्र। लाखों विचार।',
    heroSubtitle: '1% से कम को सही मार्गदर्शन मिलता है।',
    heroDesc: 'UdyamPath आपका बहुभाषी AI गुरु है — अपना विचार सत्यापित करें, स्टार्टअप यात्रा का अनुकरण करें।',
    startJourney: 'यात्रा शुरू करें',
    watchDemo: 'डेमो देखें',
    validateIdea: 'विचार सत्यापित करें',
    playSimulation: 'सिमुलेशन खेलें',
    growthPath: 'विकास पथ',
    aiCoach: 'AI कोच',
    ideaPlaceholder: 'अपना सामाजिक स्टार्टअप विचार बताएं...',
    whatIsYourIdea: 'आपका विचार क्या है?',
    analyzeIdea: 'विचार विश्लेषण करें',
    generating: 'तैयार हो रहा है...',
    loading: 'लोड हो रहा है...',
    budget: 'बजट',
    morale: 'टीम मनोबल',
    trust: 'सामुदायिक विश्वास',
    impact: 'सामाजिक प्रभाव',
    month: 'महीना',
    turn: 'पारी',
    yourDecision: 'आपका निर्णय',
    consequence: 'परिणाम',
    lesson: 'वास्तविक सबक',
    nextTurn: 'अगली पारी',
    growthDashboard: 'विकास डैशबोर्ड',
    weaknesses: 'सुधार के क्षेत्र',
    resources: 'क्यूरेटेड संसाधन',
    actionPlan: 'इस सप्ताह की कार्य योजना',
    chat: 'कोच से बात करें',
    sendMessage: 'भेजें',
    typingMessage: 'AI कोच सोच रहा है...',
    language: 'भाषा',
    switchLang: 'भाषा बदलें',
    score: 'स्कोर',
    problem: 'समस्या वैधता',
    audience: 'लक्षित दर्शक',
    market: 'बाजार आकार',
    uniqueness: 'विशिष्टता',
    emotionalMsg: 'आपका विचार प्रभावित कर सकता है',
    lakhs: 'लाख लोगों को',
    startSimulation: 'सिमुलेशन शुरू करें',
    viewDashboard: 'विकास डैशबोर्ड देखें',
    chatWithCoach: 'AI कोच से बात करें',
    schemes: 'सरकारी योजनाएं',
    videos: 'सीखने के वीडियो',
    impactScore: 'प्रभाव स्कोर',
    sustainability: 'स्थिरता',
    teamHealth: 'टीम स्वास्थ्य',
    communityTrust: 'सामुदायिक विश्वास',
    selectLanguage: 'अपनी भाषा चुनें',
    continueBtn: 'जारी रखें',
    yourLocation: 'आपका स्थान',
    yourBudget: 'प्रारंभिक बजट',
    yourSector: 'क्षेत्र',
    yourStage: 'चरण',
    locationOptions: ['टियर-1 शहर', 'टियर-2 शहर', 'टियर-3 शहर / ग्रामीण'],
    budgetOptions: ['< ₹10,000', '₹10,000 - ₹50,000', '₹50,000 - ₹2 लाख', '> ₹2 लाख'],
    sectorOptions: ['शिक्षा', 'स्वास्थ्य', 'कृषि', 'महिला सशक्तिकरण', 'पर्यावरण', 'कौशल विकास', 'अन्य'],
    stageOptions: ['बस एक विचार', 'सत्यापित विचार', 'प्रोटोटाइप', 'कुछ उपयोगकर्ता हैं'],
    ideaValidation: 'विचार सत्यापन रिपोर्ट',
    simulationTitle: 'उद्यामबोर्ड सिमुलेशन',
    dashboardTitle: 'आपका विकास डैशबोर्ड',
    coachTitle: 'AI कोच',
  },
  te: {
    tagline: 'మీ AI పారిశ్రామికవేత్త సహచరి',
    heroTitle: '4 కోట్ల విద్యార్థులు. లక్షల ఆలోచనలు.',
    heroSubtitle: '1% కంటే తక్కువ మందికి నిజమైన మార్గదర్శకత్వం లభిస్తుంది.',
    heroDesc: 'UdyamPath మీ బహుభాషా AI మార్గదర్శకుడు — మీ ఆలోచనను ధృవీకరించండి.',
    startJourney: 'నా యాత్ర ప్రారంభించండి',
    watchDemo: 'డెమో చూడండి',
    validateIdea: 'ఆలోచనను ధృవీకరించండి',
    playSimulation: 'సిమ్యులేషన్ ఆడండి',
    growthPath: 'వృద్ధి మార్గం',
    aiCoach: 'AI కోచ్',
    ideaPlaceholder: 'మీ సామాజిక స్టార్టప్ ఆలోచనను వివరించండి...',
    whatIsYourIdea: 'మీ ఆలోచన ఏమిటి?',
    analyzeIdea: 'నా ఆలోచన విశ్లేషించండి',
    generating: 'రూపొందిస్తోంది...',
    loading: 'లోడ్ అవుతోంది...',
    budget: 'బడ్జెట్',
    morale: 'జట్టు స్ఫూర్తి',
    trust: 'సమాజ విశ్వాసం',
    impact: 'సామాజిక ప్రభావం',
    month: 'నెల',
    turn: 'పర్యాయం',
    yourDecision: 'మీ నిర్ణయం',
    consequence: 'పరిణామం',
    lesson: 'నిజ జీవిత పాఠం',
    nextTurn: 'తదుపరి పర్యాయం',
    growthDashboard: 'వృద్ధి డాష్‌బోర్డ్',
    weaknesses: 'మెరుగుపడవలసిన రంగాలు',
    resources: 'ఎంపిక చేసిన వనరులు',
    actionPlan: 'ఈ వారం చర్య ప్రణాళిక',
    chat: 'కోచ్‌తో చాట్ చేయండి',
    sendMessage: 'పంపు',
    typingMessage: 'AI కోచ్ ఆలోచిస్తోంది...',
    language: 'భాష',
    switchLang: 'భాష మార్చండి',
    score: 'స్కోర్',
    problem: 'సమస్య చెల్లుబాటు',
    audience: 'లక్ష్య ప్రేక్షకులు',
    market: 'మార్కెట్ పరిమాణం',
    uniqueness: 'ప్రత్యేకత',
    emotionalMsg: 'మీ ఆలోచన ప్రభావం చూపవచ్చు',
    lakhs: 'లక్షల మందికి',
    startSimulation: 'సిమ్యులేషన్ ప్రారంభించండి',
    viewDashboard: 'వృద్ధి డాష్‌బోర్డ్ చూడండి',
    chatWithCoach: 'AI కోచ్‌తో మాట్లాడండి',
    schemes: 'ప్రభుత్వ పథకాలు',
    videos: 'నేర్చుకోవడానికి వీడియోలు',
    impactScore: 'ప్రభావ స్కోర్',
    sustainability: 'సుస్థిరత',
    teamHealth: 'జట్టు ఆరోగ్యం',
    communityTrust: 'సమాజ విశ్వాసం',
    selectLanguage: 'మీ భాష ఎంచుకోండి',
    continueBtn: 'కొనసాగించండి',
    yourLocation: 'మీ స్థానం',
    yourBudget: 'ప్రారంభ బడ్జెట్',
    yourSector: 'రంగం',
    yourStage: 'దశ',
    locationOptions: ['టైర్-1 నగరం', 'టైర్-2 నగరం', 'టైర్-3 నగరం / గ్రామీణ'],
    budgetOptions: ['< ₹10,000', '₹10,000 - ₹50,000', '₹50,000 - ₹2 లక్షలు', '> ₹2 లక్షలు'],
    sectorOptions: ['విద్య', 'ఆరోగ్యం', 'వ్యవసాయం', 'మహిళా సాధికారత', 'పర్యావరణం', 'నైపుణ్య అభివృద్ధి', 'ఇతర'],
    stageOptions: ['కేవలం ఒక ఆలోచన', 'ధృవీకరించబడిన ఆలోచన', 'ప్రాథమిక నమూనా', 'కొంతమంది వినియోగదారులు ఉన్నారు'],
    ideaValidation: 'ఆలోచన ధృవీకరణ నివేదిక',
    simulationTitle: 'UdyamBoard సిమ్యులేషన్',
    dashboardTitle: 'మీ వృద్ధి డాష్‌బోర్డ్',
    coachTitle: 'AI కోచ్',
  },
  ta: {
    tagline: 'உங்கள் AI தொழில்முனைவோர் துணைவன்',
    heroTitle: '4 கோடி மாணவர்கள். மில்லியன் கணக்கான யோசனைகள்.',
    heroSubtitle: '1%க்கும் குறைவானவர்களுக்கே உண்மையான வழிகாட்டுதல் கிடைக்கிறது.',
    heroDesc: 'UdyamPath உங்கள் பன்மொழி AI வழிகாட்டி — உங்கள் யோசனையை சரிபார்க்கவும்.',
    startJourney: 'என் பயணத்தை தொடங்கு',
    watchDemo: 'டெமோவைப் பார்',
    validateIdea: 'யோசனையை சரிபார்க்கவும்',
    playSimulation: 'சிமுலேஷன் விளையாடுங்கள்',
    growthPath: 'வளர்ச்சி பாதை',
    aiCoach: 'AI பயிற்சியாளர்',
    ideaPlaceholder: 'உங்கள் சமூக தொடக்க யோசனையை விவரிக்கவும்...',
    whatIsYourIdea: 'உங்கள் யோசனை என்ன?',
    analyzeIdea: 'என் யோசனையை பகுப்பாய்வு செய்',
    generating: 'உருவாக்குகிறது...',
    loading: 'ஏற்றுகிறது...',
    budget: 'பட்ஜெட்',
    morale: 'குழு மனோதிடம்',
    trust: 'சமுதாய நம்பிக்கை',
    impact: 'சமூக தாக்கம்',
    month: 'மாதம்',
    turn: 'திருப்பம்',
    yourDecision: 'உங்கள் முடிவு',
    consequence: 'விளைவு',
    lesson: 'நிஜ உலக பாடம்',
    nextTurn: 'அடுத்த திருப்பம்',
    growthDashboard: 'வளர்ச்சி டாஷ்போர்டு',
    weaknesses: 'மேம்படுத்த வேண்டிய பகுதிகள்',
    resources: 'தேர்ந்தெடுக்கப்பட்ட வளங்கள்',
    actionPlan: 'இந்த வாரத்தின் திட்டம்',
    chat: 'பயிற்சியாளருடன் பேசுங்கள்',
    sendMessage: 'அனுப்பு',
    typingMessage: 'AI பயிற்சியாளர் சிந்திக்கிறார்...',
    language: 'மொழி',
    switchLang: 'மொழியை மாற்றுங்கள்',
    score: 'மதிப்பெண்',
    problem: 'சிக்கல் செல்லுபடி',
    audience: 'இலக்கு பார்வையாளர்கள்',
    market: 'சந்தை அளவு',
    uniqueness: 'தனித்தன்மை',
    emotionalMsg: 'உங்கள் யோசனை பாதிக்கலாம்',
    lakhs: 'லட்சம் பேரை',
    startSimulation: 'சிமுலேஷனை தொடங்கு',
    viewDashboard: 'வளர்ச்சி டாஷ்போர்டு பார்',
    chatWithCoach: 'AI பயிற்சியாளருடன் பேசுங்கள்',
    schemes: 'அரசு திட்டங்கள்',
    videos: 'கற்றல் வீடியோக்கள்',
    impactScore: 'தாக்க மதிப்பெண்',
    sustainability: 'நிலைத்தன்மை',
    teamHealth: 'குழு ஆரோக்கியம்',
    communityTrust: 'சமுதாய நம்பிக்கை',
    selectLanguage: 'உங்கள் மொழியை தேர்ந்தெடுக்கவும்',
    continueBtn: 'தொடர்க',
    yourLocation: 'உங்கள் இருப்பிடம்',
    yourBudget: 'தொடக்க பட்ஜெட்',
    yourSector: 'துறை',
    yourStage: 'நிலை',
    locationOptions: ['அடுக்கு-1 நகரம்', 'அடுக்கு-2 நகரம்', 'அடுக்கு-3 நகரம் / கிராமப்புறம்'],
    budgetOptions: ['< ₹10,000', '₹10,000 - ₹50,000', '₹50,000 - ₹2 லட்சம்', '> ₹2 லட்சம்'],
    sectorOptions: ['கல்வி', 'சுகாதாரம்', 'வேளாண்மை', 'பெண்கள் அதிகாரமளிப்பு', 'சுற்றுச்சூழல்', 'திறன் மேம்பாடு', 'மற்றவை'],
    stageOptions: ['வெறும் யோசனை', 'சரிபார்க்கப்பட்ட யோசனை', 'ஆரம்ப மாதிரி', 'சில பயனர்கள் உள்ளனர்'],
    ideaValidation: 'யோசனை சரிபார்ப்பு அறிக்கை',
    simulationTitle: 'UdyamBoard சிமுலேஷன்',
    dashboardTitle: 'உங்கள் வளர்ச்சி டாஷ்போர்டு',
    coachTitle: 'AI பயிற்சியாளர்',
  }
};

const LANGUAGE_FLAGS = {
  en: { flag: '🇬🇧', name: 'English', nativeName: 'English' },
  hi: { flag: '🇮🇳', name: 'Hindi', nativeName: 'हिंदी' },
  te: { flag: '🏳️', name: 'Telugu', nativeName: 'తెలుగు' },
  ta: { flag: '🏳️', name: 'Tamil', nativeName: 'தமிழ்' },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;
  const langMeta = LANGUAGE_FLAGS[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, langMeta, LANGUAGE_FLAGS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export { translations };
